import { useContext } from "react";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Cards from "../components/Cards";
import Billing from "../components/Billing";
import { Heading, Box, Text } from "@chakra-ui/react";

import { BillingContext } from "../utils/BillingContext";
import { formatToCurrency } from "../utils/helpers";

export default function Home() {
  const [billing] = useContext(BillingContext);

  return (
    <Box className={styles.container} bg={"whiteAlpha.100"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading as="h2" size="xl">
          <Text
            bgGradient="linear(to-l, #7928CA, #FF0080)"
            bgClip="text"
            fontSize="6xl"
            fontWeight="extrabold"
          >
            Always be billing...
          </Text>
        </Heading>
        <Billing />
        <Cards></Cards>
      </main>

      <footer>
        <a
          href="https://nickwforsberg.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Nick W Forsberg
        </a>
      </footer>
    </Box>
  );
}
